### ISSUE TITLE
linkblueprint error

### ISSUE THREAD

**Issue by asmod3us** [jailmanager/jailman#175]
Errors with `!linkblueprint: unbound variable ERR`

config.yml:
```
global:
  # Config file syntax version (not same as script version)
  version: 1.3
  # Relevant dataset paths, please use the ZFS dataset syntax such as: tank/apps
  dataset:
    # dataset for internal jail config files
    config: tank/apps
    # Media library dataset
    media: tank/media
    # these are relative to media mountpoint in jail:
    # Parent downloads dataset
    # (is going to contain: Complete and Incomplete datasets for downloads)
    downloads: tank/downloads
    downloads_complete: tank/downloads
    downloads_incomplete: tank/incoming
  jails:
    # jail version to install
    version: 11.3-RELEASE
    # Global pkgs to install in all jails.
    # Please use standard space delimited pkg install syntax.
    pkgs: curl ca_root_nss bash

jail:

  sabnzbd:
    blueprint: sabnzbd
    dhcp: override
    domain_name: sabnzbd.my.domain
    link_traefik: traefik

  traefik:
    blueprint: traefik
    dashboard: true
    domain_name: traefik.my.domain
    dns_provider: cloudflare
    cert_email: fake@email.net
    cert_wildcard_domain: my.domain
    cert_env:
      CF_API_EMAIL: your@login.com
      CF_API_KEY: YOURPASSWORD
```

**Comment by uofirob** [comment]
Let me know what you'd like me to add to this thread for you to track it down

**Comment by asmod3us** [comment]
Edit: it craps out if there is no link_traefik, i.e. change to above config:

```
jail:

  sabnzbd3:
    blueprint: sabnzbd
    dhcp: on
    domain_name: sabnzbd.my.domain
```

debug.log of failing part:
```
+ echo 'Jail creation completed for sabnzbd3'
Jail creation completed for sabnzbd3
+ /mnt/tank/sys-new/jm/blueprints/sabnzbd/install.sh sabnzbd3
+ initblueprint sabnzbd3
+ source /mnt/tank/sys-new/jm/includes/libstrict.sh
++ export -f strict::failure
++ export -f warn
++ export -f strict::mode
+ strict::mode
+ set -o errexit
+ set -o errtrace
+ set -o nounset
+ set -o pipefail
+ trap 'strict::failure $?' ERR
+ export SHELLOPTS
+ local jail_name blueprint varlist linkblueprint linkvarlist value val linkvalue linkval
+ jail_name=sabnzbd3
+ blueprint=jail_sabnzbd3_blueprint
+ varlist=blueprint_sabnzbd_vars
+ for var in ${!varlist:-} ${global_jails_vars}
+ value=jail_sabnzbd3_ip4_addr
+ val=
+ declare -g ip4_addr=
+ [[ ip4_addr =~ ^link_.* ]]
+ for var in ${!varlist:-} ${global_jails_vars}
+ value=jail_sabnzbd3_host_name
+ val=
+ declare -g host_name=
+ [[ host_name =~ ^link_.* ]]
+ for var in ${!varlist:-} ${global_jails_vars}
+ value=jail_sabnzbd3_gateway
+ val=
+ declare -g gateway=
+ [[ gateway =~ ^link_.* ]]
+ for var in ${!varlist:-} ${global_jails_vars}
+ value=jail_sabnzbd3_link_traefik
+ val=
+ declare -g link_traefik=
+ [[ link_traefik =~ ^link_.* ]]
+ linkblueprint=jail__blueprint
environment: line 13: !linkblueprint: unbound variable
++ strict::failure 1
++ set +x
ERR - status code 1
Command:  "${SCRIPT_DIR}"/blueprints/"${!blueprint}"/install.sh "${jail}"
Location:  jailman.sh, line 192
Status: 0
Stack trace:
    [1] main(): jailman.sh, line 192 -> main
```
